sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_install:
    - rustup component add clippy-preview --toolchain=nightly

env:
  global:
    - RUST_BACKTRACE=1

matrix:
    include:
        - rust: stable
          script:
              - cargo build
              - cargo test
              - cargo test --ignored
        - rust: beta
          script:
              - cargo build
              - cargo test
              - cargo test --ignored
        - rust: nightly
          script:
              - cargo build
              - cargo test
              - cargo test --ignored
              - cargo clippy
              - cargo clippy --tests

